package ui;

import core.util.FileUtils;
import encoder.bean.CodingType;
import encoder.file.FileEncoder;
import java.io.File;
import java.text.ParseException;
import java.util.Arrays;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * Janela principal do programa de codificacao e decodificacao de arquivos
 */
public class FileEncoderWindow extends javax.swing.JFrame {

    private File file;
    private FileEncoder fileEncoder;
    private JFileChooser fileChooser;

    public FileEncoderWindow() {
        initComponents();
        this.fileEncoder = new FileEncoder();
        this.fileChooser = new JFileChooser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCodingTypeField = new javax.swing.JComboBox<>();
        jDividerField = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jEncodeButton = new javax.swing.JButton();
        jFileChooser = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jFilePath = new javax.swing.JLabel();
        jDecodeButton = new javax.swing.JButton();
        jGenerateEccButton = new javax.swing.JButton();
        jExtractEccButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Codificador/Decodificador");
        setResizable(false);

        jCodingTypeField.setModel(_getCodingTypeOptions());
        jCodingTypeField.setEnabled(false);
        jCodingTypeField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCodingTypeFieldPropertyChange(evt);
            }
        });

        jDividerField.setModel(new javax.swing.SpinnerNumberModel(2, 2, 512, 1));
        jDividerField.setEnabled(false);

        jLabel2.setText("Divisor");

        jEncodeButton.setText("Codificar");
        jEncodeButton.setEnabled(false);
        jEncodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEncodeButtonActionPerformed(evt);
            }
        });

        jFileChooser.setText("Selecionar arquivo");
        jFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserActionPerformed(evt);
            }
        });

        jFilePath.setText("Nenhum arquivo selecionado");

        jDecodeButton.setText("Decodificar");
        jDecodeButton.setEnabled(false);
        jDecodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDecodeButtonActionPerformed(evt);
            }
        });

        jGenerateEccButton.setText("Gerar arquivo ECC");
        jGenerateEccButton.setEnabled(false);
        jGenerateEccButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenerateEccButtonActionPerformed(evt);
            }
        });

        jExtractEccButton.setText("Extrair arquivo ECC");
        jExtractEccButton.setEnabled(false);
        jExtractEccButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExtractEccButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDecodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jGenerateEccButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jExtractEccButton)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFilePath))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jEncodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCodingTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDividerField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFileChooser)
                    .addComponent(jFilePath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCodingTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDividerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jEncodeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDecodeButton)
                    .addComponent(jGenerateEccButton)
                    .addComponent(jExtractEccButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCodingTypeField.getAccessibleContext().setAccessibleName("");
        jCodingTypeField.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jCodingTypeFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCodingTypeFieldPropertyChange
        _enableDisableDividerField();
    }//GEN-LAST:event_jCodingTypeFieldPropertyChange

    private void jFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserActionPerformed
        if (fileChooser.showOpenDialog(FileEncoderWindow.this) == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
            jFilePath.setText(file.getAbsolutePath());
            jEncodeButton.setEnabled(true);
            jCodingTypeField.setEnabled(true);
            _enableDisableDividerField();
            jDecodeButton.setEnabled(FileUtils.checkExtensionName(file, "enc"));
            jGenerateEccButton.setEnabled(FileUtils.checkExtensionName(file, "enc"));
            jExtractEccButton.setEnabled(FileUtils.checkExtensionName(file, "ecc"));
        }
    }//GEN-LAST:event_jFileChooserActionPerformed

    private void jEncodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEncodeButtonActionPerformed
        CodingType coding = CodingType.findByName((String) jCodingTypeField.getSelectedItem());
        File output = fileEncoder.encode(file, coding, _getDivider());
        JOptionPane.showMessageDialog(null, "O arquivo " + file.getName() + " passou de " + file.length() + " bytes para " + output.length() + " bytes");
    }//GEN-LAST:event_jEncodeButtonActionPerformed

    private void jDecodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDecodeButtonActionPerformed
        fileEncoder.decode(file);
        JOptionPane.showMessageDialog(null, "O arquivo " + file.getName() + " foi decodificado com sucesso!");
    }//GEN-LAST:event_jDecodeButtonActionPerformed

    private void jGenerateEccButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenerateEccButtonActionPerformed
        File output = fileEncoder.generateEcc(file);
        JOptionPane.showMessageDialog(null, "O arquivo " + output.getName() + " foi gerado!");
    }//GEN-LAST:event_jGenerateEccButtonActionPerformed

    private void jExtractEccButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExtractEccButtonActionPerformed
        File output = fileEncoder.extractEcc(file);
        JOptionPane.showMessageDialog(null, "O arquivo " + output.getName() + " foi gerado!");
    }//GEN-LAST:event_jExtractEccButtonActionPerformed

    private void _enableDisableDividerField() {
        boolean isEnabled = Objects.nonNull(file) && "Golomb".equals((String) jCodingTypeField.getSelectedItem());
        jDividerField.setEnabled(isEnabled);
    }

    private int _getDivider() {
        try {
            jDividerField.commitEdit();
        } catch (ParseException ex) {
            Logger.getLogger(FileEncoderWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        return (int) jDividerField.getValue();
    }

    private DefaultComboBoxModel _getCodingTypeOptions() {
        String[] options = Arrays.asList(CodingType.values()).stream()
                .map(coding -> coding.getName())
                .toArray(size -> new String[size]);
        return new DefaultComboBoxModel(options);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileEncoderWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FileEncoderWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCodingTypeField;
    private javax.swing.JButton jDecodeButton;
    private javax.swing.JSpinner jDividerField;
    private javax.swing.JButton jEncodeButton;
    private javax.swing.JButton jExtractEccButton;
    private javax.swing.JButton jFileChooser;
    private javax.swing.JLabel jFilePath;
    private javax.swing.JButton jGenerateEccButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
